config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get    "tasks",          to: "tasks#index"

  get    "tasks/new",      to: "tasks#new", as: :new
  post   "tasks",          to: "tasks#create"

  # NB: The `show` route needs to be *after* `new` route.
  get    "tasks/:id",      to: "tasks#show", as: :task

  get    "tasks/:id/edit", to: "tasks#edit", as: :edit
  patch  "tasks/:id",      to: "tasks#update"

  delete "tasks/:id",      to: "tasks#destroy", as: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  # before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index         # GET /tasks
    @tasks = Task.all
  end

  def show          # GET /tasks/:id
    @task = Task.find(params[:id])
  end

  def new           # GET /tasks/new
    @task = Task.new
  end

  def create        # POST /tasks
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task)
  end

  def edit          # GET /tasks/:id/edit
    @task = Task.find(params[:id])

  end

  def update        # PATCH /tasks/:id
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy       # DELETE /tasks/:id
    @task = Task.find(params[:id])
    @task.destroy

    redirect_to tasks_path
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/destroy.html.erb
<%= link_to "Back to list", tasks_path%>

app/views/tasks/edit.html.erb
<div class="container">
<h1>Edit</h1>

<%= form_for(@task) do |f| %>
<div class="form-group">
  <%= f.label :title %>
  <%= f.text_field :title, class: 'form-control' %>
</div>

<div class="form-group">
  <%= f.label :details %>
  <%= f.text_field :details, class: 'form-control' %>
</div>

<div class="form-group">
  <%= f.label :completed %>
  <%= f.check_box :completed, class: 'form-control' %>
</div>

  <%= f.submit class: 'btn btn-primary'%>
<% end %>

<%= link_to "Back to list", tasks_path%>
</div>

app/views/tasks/index.html.erb
<div class="container">
<h1>My tasks</h1>

<% @tasks.each do |task| %>
  <%= link_to task.title, task_path(task) %>
  <p><%= task.details %></p>
<% end %>

<%= link_to("New task", new_path, class: 'btn btn-primary') %>

app/views/tasks/new.html.erb
<div class="container">
<%= form_for(@task) do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :details %>
    <%= f.text_field :details, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :completed %>
    <%= check_box("task", "completed") %>
  </div>

  <%= f.submit class: 'btn btn-primary' %>
<% end %>


<%= link_to "Back to list", tasks_path %>
</div>

app/views/tasks/show.html.erb
<div class="container">
  <h2><%= @task.title %></h2>
  <p><%= @task.details %></p>

  <div class="custom-control custom-checkbox">
  <%= check_box("task", "completed") %>
  <label class="form-check-label" for="inlineCheckbox">Completed</label>
  </div>

  <div>
  <%= link_to "Edit", edit_path, class: 'btn btn-primary'%>
  <%= link_to "Destroy", destroy_path, class: 'btn btn-danger', method: :delete, data: { confirm: "Are you sure?" }%>
  <%= link_to "Back to list", tasks_path%>
  </div>
</div>